import { useState } from "react";
import { createRoot } from "react-dom/client";
import type { BenchmarkRun } from "./types";
import { ResultsTable } from "./components/results-table";
import {
  ModelComparisonChart,
  TokensPerSecondChart,
} from "./components/charts";
import { StatsCards } from "./components/stats-cards";
import { SummariesSection } from "./components/summaries";

function App() {
  const data: BenchmarkRun = window.BENCHMARK_DATA;
  const [activeTab, setActiveTab] = useState<"table" | "charts">("table");

  const formatDate = (timestamp: string) => {
    return new Date(timestamp).toLocaleString("en-US", {
      dateStyle: "medium",
      timeStyle: "short",
    });
  };

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="border-b border-surface-300 bg-surface-100/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-2xl font-bold bg-gradient-to-r from-accent-400 to-cyan-300 bg-clip-text text-transparent">
                DEX Bench
              </h1>
              <span className="px-2 py-1 text-xs font-mono bg-surface-300 rounded-md text-gray-400">
                LLM Benchmark
              </span>
            </div>
            <div className="flex items-center gap-6 text-sm text-gray-400">
              <span className="font-mono">{data.id}</span>
              <span>{formatDate(data.timestamp)}</span>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        {/* Stats Overview */}
        <StatsCards
          stats={data.stats}
          models={data.models}
          documents={data.documents}
        />

        {/* Tab Navigation */}
        <div className="flex gap-2 mb-6 mt-8">
          <button
            type="button"
            onClick={() => setActiveTab("table")}
            className={`px-4 py-2 rounded-lg font-medium transition-all ${
              activeTab === "table"
                ? "bg-accent-500 text-surface-50"
                : "bg-surface-200 text-gray-400 hover:bg-surface-300 hover:text-gray-200"
            }`}
          >
            Results Table
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("charts")}
            className={`px-4 py-2 rounded-lg font-medium transition-all ${
              activeTab === "charts"
                ? "bg-accent-500 text-surface-50"
                : "bg-surface-200 text-gray-400 hover:bg-surface-300 hover:text-gray-200"
            }`}
          >
            Charts
          </button>
        </div>

        {/* Content */}
        {activeTab === "table" ? (
          <div className="card">
            <ResultsTable results={data.results} />
          </div>
        ) : (
          <div className="grid gap-6 lg:grid-cols-2">
            <div className="card chart-container">
              <h3 className="text-lg font-semibold mb-4 text-gray-200">
                Average Duration by Model
              </h3>
              <ModelComparisonChart modelAverages={data.stats.modelAverages} />
            </div>
            <div className="card chart-container">
              <h3 className="text-lg font-semibold mb-4 text-gray-200">
                Tokens per Second
              </h3>
              <TokensPerSecondChart results={data.results} />
            </div>
          </div>
        )}

        {/* Summaries */}
        <div className="mt-8">
          <SummariesSection results={data.results} />
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-surface-300 mt-16 py-6">
        <div className="max-w-7xl mx-auto px-6 text-center text-sm text-gray-500">
          Generated by DEX Bench • {data.models.length} models •{" "}
          {data.documents.length} documents
        </div>
      </footer>
    </div>
  );
}

const rootElement = document.getElementById("root");
if (rootElement) {
  const root = createRoot(rootElement);
  root.render(<App />);
}
